### PR TITLE
Update #18

### PR DESCRIPTION
**Pull request by rpitingolo**
@NeighborhoodInfoDC/review requesting a review. 

The following variables are no longer on the raw data file: 

- Agency
- Appdate
- Edit

I had to adjust a few formats as well. The current HMDA formats are shown here: https://ffiec.cfpb.gov/documentation/2018/lar-data-fields/

I  think the format program needs to get batch submitted first? I committed the changes on this branch.

### CODE REVIEW

**Comment by rpitingolo** [comment]
@NeighborhoodInfoDC/review re-tagging this review request in case it got lost on Friday. Thanks!

**Comment by lhendey** [comment]
@ptatian are you able to review? I haven't looked at these before. @rpitingolo

**Comment by ptatian** [comment]
@rpitingolo @lhendey Yes, sorry. I'll try to look at this in a little bit.

**Comment by rpitingolo** [comment]
Thanks @ptatian

**Comment by ptatian** [comment]
Long run time. :smile:

**Review by ptatian — APPROVED** [review]
@rpitingolo Looks good. I noted uninitialized variable messages for `appdate` and `respondent_id`, but they don't seem to be causing any problems in the final data set.

**Comment by rpitingolo** [comment]
@ptatian thanks. I'll take a second look at those two variables before I finalize.

**Comment by rpitingolo** [comment]
@ptatian those two variables were leftover from previous years and not in the 2018 loan-level file. I removed them from the code as they don't impact the output.

**Pull request merged**
