### PR TITLE
HMDA update #2

### PR DESCRIPTION
**Pull request by ahariharan7**
@rpitingolo The data isn't reading in and I don't know why SOS

### CODE REVIEW

**Comment by rpitingolo** [comment]
@ahariharan7 I'll take a look.

**Comment by rpitingolo** [comment]
@ahariharan7 OK so we need to create a macro called %hud_inc_2019 which will put the income variable into categories based on the HUD cutoffs. This is in the ipums repo so I'll make an issue over there and tag you on it.

**Comment by rpitingolo** [comment]
@ahariharan7 please go ahead and re-test now that we have updated %hud_inc_2019

**Comment by ahariharan7** [comment]
@rpitingolo still not working!!!!

**Comment by rpitingolo** [comment]
@ahariharan7 are you getting errors in the log or is it the output that doesn't look right?

**Comment by ahariharan7** [comment]
Whoops - it's that the output says that no data are being read in.
________________________________

**Comment by rpitingolo** [comment]
@ahariharan7  I think something weird is up with your virtual environment. Because I am not able to replicate the issue. Let's meet quickly today so you can show me what happens on your screen.

**Comment by rpitingolo** [comment]
@ahariharan7 Good to merge, sync and finalize this one. Thanks!

**Pull request merged**
